server:
  port:
    8060


spring:
  profiles.active: default

---

spring:

  profiles: default
  data:
    mongodb:
      database: Payments
      port: 27017
      host: localhost

---

spring:
  profiles: application-dev

  url: https://api-sys-test.di-ro.com

  data:
    mongodb:

      uri: mongodb+srv://asd:Aa123456@diro-test.c0px2.mongodb.net/myFirstDatabase?retryWrites=true&w=majority